version: '3'
services:
  zookeeper-bank:
    image: confluentinc/cp-zookeeper:7.0.1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - bank_net

  kafka-bank:
    image: confluentinc/cp-kafka:7.0.1
    container_name: "kafka-bank"
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper-bank
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: ${KAFKA_CFG_ZOOKEEPER_CONNECT}
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${KAFKA_CLIENT_HOST}:9092,PLAINTEXT_INTERNAL://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - bank_net

volumes:
  bank_zookeeper_data:
    driver: local
  bank_kafka_data:
    driver: local