version: "2"

services:
  zookeeper-bank:
    image: "bitnami/zookeeper:3.8"
    ports:
      - "2181:2181"
    volumes:
      - "bank_zookeeper_data:/bitnami"
    environment:
      - ZOO_ENABLE_AUTH=${ZOO_ENABLE_AUTH}
      - ZOO_SERVER_USERS=${ZOO_SERVER_USERS}
      - ZOO_SERVER_PASSWORDS=${ZOO_SERVER_PASSWORDS}

  kafka-bank:
    image: "bitnami/kafka:3.3"
    ports:
      - "9092:9092"
    volumes:
      - "bank_kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=${KAFKA_CFG_ZOOKEEPER_CONNECT}
      - ALLOW_PLAINTEXT_LISTENER=${ALLOW_PLAINTEXT_LISTENER}
      - KAFKA_ZOOKEEPER_USER=${KAFKA_ZOOKEEPER_USER}
      - KAFKA_ZOOKEEPER_PASSWORD=${KAFKA_ZOOKEEPER_PASSWORD}
      - KAFKA_CLIENT_USERS=${KAFKA_CLIENT_USERS}
      - KAFKA_CLIENT_PASSWORDS=${KAFKA_CLIENT_PASSWORDS}
    depends_on:
      - zookeeper-bank

volumes:
  bank_zookeeper_data:
    driver: local
  bank_kafka_data:
    driver: local
