FROM postgres:13.5-bullseye
COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh
#ENTRYPOINT [""]
#CMD ["/usr/local/bin/docker-entrypoint.sh postgres"]
#CMD ["/bin/sh", "-c", "sleep 3600"]